version: '3'

services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PGPORT=5432
      - PORT=5000
      # - PGHOST=postgres
      # - PGDATABASE=postgres
      # - PGUSER=postgres
      # - PGPASSWORD=postgres
    depends_on:
      - postgres
      - nginx
    volumes:
      - /app/node_modules
      - ./backend:/app 

  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
      - nginx
    environment:
      - CHOKIDAR_USEPOLLING="true"
    volumes:
      - /app/node_modules
      - ./frontend:/app 

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'