const MOVIE_ADD_REQUEST = 'MOVIE_ADD_REQUEST';
const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS';
const MOVIE_ADD_FAILURE = 'MOVIE_ADD_FAILURE';

const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE';

const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
const MOVIE_DELETE_FAILURE = 'MOVIE_DELETE_FAILURE';

const MOVIE_SINGLE_REQUEST = 'MOVIE_SINGLE_REQUEST';
const MOVIE_SINGLE_SUCCESS = 'MOVIE_SINGLE_SUCCESS';
const MOVIE_SINGLE_FAILURE = 'MOVIE_SINGLE_FAILURE';

const MOVIE_EDIT_REQUEST = 'MOVIE_EDIT_REQUEST';
const MOVIE_EDIT_SUCCESS = 'MOVIE_EDIT_SUCCESS';
const MOVIE_EDIT_FAILURE = 'MOVIE_EDIT_FAILURE';

const MOVIE_ADD_DIRECTOR_REQUEST = 'MOVIE_ADD_DIRECTOR_REQUEST';
const MOVIE_ADD_DIRECTOR_SUCCESS = 'MOVIE_ADD_DIRECTOR_SUCCESS';
const MOVIE_ADD_DIRECTOR_FAILURE = 'MOVIE_ADD_DIRECTOR_FAILURE';

const MOVIE_DELETE_DIRECTOR_REQUEST = 'MOVIE_DELETE_DIRECTOR_REQUEST';
const MOVIE_DELETE_DIRECTOR_SUCCESS = 'MOVIE_DELETE_DIRECTOR_SUCCESS';
const MOVIE_DELETE_DIRECTOR_FAILURE = 'MOVIE_DELETE_DIRECTOR_FAILURE';

 const types = {
    MOVIE_ADD_REQUEST,
    MOVIE_ADD_SUCCESS,
    MOVIE_ADD_FAILURE,
    MOVIE_LIST_REQUEST,
    MOVIE_LIST_SUCCESS,
    MOVIE_LIST_FAILURE,
    MOVIE_DELETE_REQUEST,
    MOVIE_DELETE_SUCCESS,
    MOVIE_DELETE_FAILURE,
    MOVIE_SINGLE_REQUEST,
    MOVIE_SINGLE_SUCCESS,
    MOVIE_SINGLE_FAILURE,
    MOVIE_EDIT_REQUEST,
    MOVIE_EDIT_SUCCESS,
    MOVIE_EDIT_FAILURE,
    MOVIE_ADD_DIRECTOR_REQUEST,
    MOVIE_ADD_DIRECTOR_SUCCESS,
    MOVIE_ADD_DIRECTOR_FAILURE,
    MOVIE_DELETE_DIRECTOR_REQUEST,
    MOVIE_DELETE_DIRECTOR_SUCCESS,
    MOVIE_DELETE_DIRECTOR_FAILURE
};

export default types;